title: Jessica Klusmeyer
description: Ph.D. candidate in Astronomy Â· New Mexico State University

theme: jekyll-theme-cayman

url: "https://jaklusmeyer.github.io"
baseurl: ""

header_pages:
  - about.md
  - projects.md
  - publications.md
