title: "Jessica K
description: "PhD candidate in Astronomy at New Mexico State University â€” Instrumentation, Radial Velocities, Meteor Fragmentation"
theme: minima

header_pages:
  - about.md
  - projects.md
  - publications.md
