title: "Jessica "
description: "PhD candidate in Astronomy â€” Faint Meteor Flares, Astronomical Instrumentation, Radial Velocity."
theme: minima

url: "https://jaklusmeyer.github.io"
baseurl: ""

header_pages:
  - about.md
  - projects.md
  - publications.md
