title: Jessica Klusmeyer
description: Ph.D. candidate in Astronomy Â· New Mexico State University
theme: minima

# Top navigation
header_pages:
  - projects.md
  - publications.md

# Optional: cleaner URLs
permalink: pretty
