title: "Jessica Klusmeyer"
description: "PhD candidate in Astronomy"

remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme

url: "https://jaklusmeyer.github.io"
baseurl: ""

header_pages:
  - about.md
  - projects.md
  - publications.md
